In [ ]:
import csv
import random
import math
import pandas as pd
import numpy as np
import functools
from functools import reduce
import operator
from pandas import DataFrame


def NOT(o):
    x = int(not(int(o)))
    return x
NOT('1')

#and list
def AND(l):
    l = [int(i) for i in l] 
    return functools.reduce(operator.and_, l)
AND(['1','1','1','1'])

#nand list
def NAND(l):
    l = [int(i) for i in l] 
    return int(not(AND(l)))
NAND(['1','1','0'])

#OR list
def OR(l):
    l= [int(i) for i in l]
    return functools.reduce(operator.or_,l)
OR(['1','0','0'])

#nor list
def NOR(l):
    l = [int(i) for i in l]
    return int(not(OR(l)))
NOR(['0','0','0'])

#xor list 
def XOR(values):
    result = 0
    for value in values:
        result ^= int(value)
    return result
XOR(['1','1','1'])


n=36
x=2**n
# x1=-(x/2)
# x2=(x/2)-1
limit=math.ceil((0.0001*x)/100)
sample_values=set([])
while (not(len(sample_values) == limit)):
#       bit=bin(random.getrandbits(n))[2:].zfill(n)
#     if bit not in sample_values:
        sample_values.add(bin(random.getrandbits(n))[2:].zfill(n))
        
N=list(sample_values)
df=pd.DataFrame(columns=['input','output'])
sample_values = None


#000010100100111111110100000010011101
for i in range(0,limit):
    N118 = NOT(int(N[i][0])) #1
    N119 = NOT(int(N[i][1])) #0
    N122 = NOT(int(N[i][3])) #0
    N123 = NOT(int(N[i][5])) #0
    N126 = NOT(int(N[i][7]))
    N127 = NOT(int(N[i][9]))
    N130 = NOT(int(N[i][11]))
    N131 = NOT(int(N[i][13]))
    N134 = NOT(int(N[i][15]))
    N135 = NOT(int(N[i][17]))
    N138 = NOT(int(N[i][19]))
    N139 = NOT(int(N[i][21]))
    N142 = NOT(int(N[i][23]))
    N143 = NOT(int(N[i][25]))
    N146 = NOT(int(N[i][27]))
    N147 = NOT(int(N[i][29]))
    N150 = NOT(int(N[i][31]))
    N151 = NOT(int(N[i][33]))
    N154 = NAND([N118, int(N[i][1])]) #0
    N157 = NOR([int(N[i][2]), N119])
    N158 = NOR([int(N[i][4]), N119])
    N159 = NAND([N122, int(N[i][5])])
    N162 = NAND([N126, int(N[i][9])])
    N165 = NAND([N130, int(N[i][13])])
    N168 = NAND([N134, int(N[i][17])])
    N171 = NAND([N138, int(N[i][21])])
    N174 = NAND([N142, int(N[i][25])])
    N177 = NAND([N146, int(N[i][29])])
    N180 = NAND([N150, int(N[i][33])])
    N183 = NOR([int(N[i][6]), N123])
    N184 = NOR([int(N[i][8]), N123])
    N185 = NOR([int(N[i][10]), N127])
    N186 = NOR([int(N[i][12]), N127])
    N187 = NOR([int(N[i][14]), N131])
    N188 = NOR([int(N[i][16]), N131])
    N189 = NOR([int(N[i][18]), N135])
    N190 = NOR([int(N[i][20]), N135])
    N191 = NOR([int(N[i][22]), N139])
    N192 = NOR([int(N[i][24]), N139])
    N193 = NOR([int(N[i][26]), N143])
    N194 = NOR([int(N[i][28]), N143])
    N195 = NOR([int(N[i][30]), N147])
    N196 = NOR([int(N[i][32]), N147])
    N197 = NOR([int(N[i][34]), N151])
    N198 = NOR([int(N[i][35]), N151])
    N199 = AND([N154, N159, N162, N165, N168, N171, N174, N177, N180])
    N203 = NOT(N199)
    N213 = NOT(N199)
    N223 = NOT(N199)
    N224 = XOR([N203, N154])
    N227 = XOR([N203, N159])
    N230 = XOR([N203, N162])
    N233 = XOR([N203, N165])
    N236 = XOR([N203, N168])
    N239 = XOR([N203, N171])
    N242 = NAND([int(N[i][0]), N213])
    N243 = XOR([N203, N174])
    N246 = NAND([N213, int(N[i][3])])
    N247 = XOR([N203, N177])
    N250 = NAND([N213, int(N[i][7])])
    N251 = XOR([N203, N180])
    N254 = NAND([N213, int(N[i][11])])
    N255 = NAND([N213, int(N[i][15])])
    N256 = NAND([N213, int(N[i][19])])
    N257 = NAND([N213, int(N[i][23])])
    N258 = NAND([N213, int(N[i][27])])
    N259 = NAND([N213, int(N[i][31])])
    N260 = NAND([N224, N157])
    N263 = NAND([N224, N158])
    N264 = NAND([N227, N183])
    N267 = NAND([N230, N185])
    N270 = NAND([N233, N187])
    N273 = NAND([N236, N189])
    N276 = NAND([N239, N191])
    N279 = NAND([N243, N193])
    N282 = NAND([N247, N195])
    N285 = NAND([N251, N197])
    N288 = NAND([N227, N184])
    N289 = NAND([N230, N186])
    N290 = NAND([N233, N188])
    N291 = NAND([N236, N190])
    N292 = NAND([N239, N192])
    N293 = NAND([N243, N194])
    N294 = NAND([N247, N196])
    N295 = NAND([N251, N198])
    N296 = AND([N260, N264, N267, N270, N273, N276, N279, N282, N285])
    N300 = NOT(N263)
    N301 = NOT(N288)
    N302 = NOT(N289)
    N303 = NOT(N290)
    N304 = NOT(N291)
    N305 = NOT(N292)
    N306 = NOT(N293)
    N307 = NOT(N294)
    N308 = NOT(N295)
    N309 = NOT(N296)
    N319 = NOT(N296)
    N329 = NOT(N296)
    N330 = XOR([N309, N260])
    N331 = XOR([N309, N264])
    N332 = XOR([N309, N267])
    N333 = XOR([N309, N270])
    N334 = NAND([int(N[i][2]), N319])
    N335 = XOR([N309, N273])
    N336 = NAND([N319, int(N[i][6])])
    N337 = XOR([N309, N276])
    N338 = NAND([N319, int(N[i][10])])
    N339 = XOR([N309, N279])
    N340 = NAND([N319, int(N[i][14])])
    N341 = XOR([N309, N282])
    N342 = NAND([N319, int(N[i][18])])
    N343 = XOR([N309, N285])
    N344 = NAND([N319, int(N[i][22])])
    N345 = NAND([N319, int(N[i][26])])
    N346 = NAND([N319, int(N[i][30])])
    N347 = NAND([N319, int(N[i][34])])
    N348 = NAND([N330, N300])
    N349 = NAND([N331, N301])
    N350 = NAND([N332, N302])
    N351 = NAND([N333, N303])
    N352 = NAND([N335, N304])
    N353 = NAND([N337, N305])
    N354 = NAND([N339, N306])
    N355 = NAND([N341, N307])
    N356 = NAND([N343, N308])
    N357 = AND([N348, N349, N350, N351, N352, N353, N354, N355, N356])
    N360 = NOT(N357)
    N370 = NOT(N357)
    N371 = NAND([int(N[i][4]), N360])
    N372 = NAND([N360, int(N[i][8])])
    N373 = NAND([N360, int(N[i][12])])
    N374 = NAND([N360, int(N[i][16])])
    N375 = NAND([N360, int(N[i][20])])
    N376 = NAND([N360, int(N[i][24])])
    N377 = NAND([N360, int(N[i][28])])
    N378 = NAND([N360, int(N[i][32])])
    N379 = NAND([N360, int(N[i][35])])
    N380 = NAND([int(N[i][1]), N242, N334, N371])
    N381 = NAND([N246, N336, N372, int(N[i][5])])
    N386 = NAND([N250, N338, N373, int(N[i][9])])
    N393 = NAND([N254, N340, N374, int(N[i][13])])
    N399 = NAND([N255, N342, N375, int(N[i][17])])
    N404 = NAND([N256, N344, N376, int(N[i][21])])
    N407 = NAND([N257, N345, N377, int(N[i][25])])
    N411 = NAND([N258, N346, N378, int(N[i][29])])
    N414 = NAND([N259, N347, N379, int(N[i][33])])
    N415 = NOT(N380)
    N416 = AND([N381, N386, N393, N399, N404, N407, N411, N414])
    N417 = NOT(N393)
    N418 = NOT(N404)
    N419 = NOT(N407)
    N420 = NOT(N411)
    N421 = NOR([N415, N416])
    N422 = NAND([N386, N417])
    N425 = NAND([N386, N393, N418, N399])
    N428 = NAND([N399, N393, N419])
    N429 = NAND([N386, N393, N407, N420])
    N430 = NAND([N381, N386, N422, N399])
    N431 = NAND([N381, N386, N425, N428])
    N432 = NAND([N381, N422, N425, N429])
    out= str(N223)+str(N329)+str(N370)+str(N421)+str(N430)+str(N431)+str(N432)
    #     print(out)
    #a=list(N[i])
    df.at[i,"input"]=list(N[i])
    df.at[i,"output"]=list(out)
    
    #df2=df.assign(output=out)
    #df2
    #df["OUTPUT"]=out
    
df2=pd.DataFrame(df["input"].to_list(),columns=['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35'])
df3=pd.DataFrame(df["output"].to_list(),columns=['36','37','38','39','40','41','42'])
#
#merge_list = pd.concat([df2, df3], axis=1)
df2.to_csv('x_data.csv', index=False) # save x inputs in csv file
df3.to_csv('y_data.csv', index=False) # save y outputs in csv file

#print(merge_list)
#merge_list.to_csv('data.csv')
#merge_list.to_csv('data.csv', index=False)

#input_x=np.array(df2.astype(float)).reshape(-1,1,36)
#output_y=np.array(df3.astype(float)).reshape(-1,1,7)
inital_key_value=[0,1,0,1,1,0,1,1,1,0,1,0,1,0,0,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,1,0]

In [ ]:
import numpy as np
# import pandas as pd

from sklearn.model_selection import train_test_split


x_data = np.loadtxt("x_data.csv",skiprows = 1, delimiter = ',', dtype = np.uint8)

# x_data=pd.read_csv('x_data.csv') #read x inputs
#x_data.head()

y_data=np.loadtxt("y_data.csv",skiprows = 1, delimiter = ',', dtype = np.uint8)
# y_data=pd.read_csv('y_data.csv') #read y inputs

x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2) # split data into train and test
print(x_train.shape) #=(54976, 36)
#print(y_train.shape) = (54976, 7)
#print(x_test.shape)  = (13744, 36)
#print(y_test.shape)  = (13744, 7)


(54976, 36)


In [ ]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
# reshape input data to fit LSTM
import numpy as np
num_of_train_data=54976
time_step=36
seq_len=1
x_train = np.reshape(x_train, (num_of_train_data,time_step ,seq_len))

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [ ]:
model = Sequential()
model.add(LSTM(units=36, return_sequences=True, input_shape=(time_step, seq_len))) #first layer 
#model.add(Dropout(0.2))
model.add(LSTM(units=10, return_sequences=True))
#model.add(Dropout(0.2))


model.add(LSTM(units=10, return_sequences=True))
model.add(LSTM(units=10, return_sequences=True))
model.add(LSTM(units=10, return_sequences=True))
#model.add(Dropout(0.2))
model.add(LSTM(units=10, return_sequences=True))
#model.add(Dropout(0.2))

model.add(LSTM(units=10))# second layer
#model.add(Dropout(0.2))
model.add(Dense(units = 7, activation="sigmoid"))# last layer
model.compile(optimizer = 'adam', loss = 'mean_squared_error')
model.fit(x_train, y_train, batch_size=32,epochs=100, validation_split = 0.2, verbose=1,shuffle=True)
#model.fit(x_train, y_train, epochs = 100, batch_size = 32)





In [61]:
with tf.device('/device:GPU:0'): 
  model = Sequential()
  model.add(LSTM(units=36, return_sequences=True, input_shape=(time_step, seq_len))) #first layer 
#model.add(Dropout(0.2))
  #model.add(LSTM(units=10, return_sequences=True))
#model.add(Dropout(0.2))


  #model.add(LSTM(units=10, return_sequences=True))
  #model.add(LSTM(units=10, return_sequences=True))
  #model.add(LSTM(units=10, return_sequences=True))
#model.add(Dropout(0.2))
  #model.add(LSTM(units=10, return_sequences=True))
#model.add(Dropout(0.2))

  model.add(LSTM(units=50))# second layer at 20 acc=90.45%
#model.add(Dropout(0.2))
  model.add(Dense(units = 7, activation="sigmoid"))# last layer
  #opt=tf.keras.optimizers.SGD(learning_rate=0.1, momentum=0.9)
  model.compile(optimizer = 'adam', loss = 'mean_squared_error')
  model.fit(x_train, y_train, batch_size=32,epochs=100, validation_split = 0.2, verbose=1,shuffle=True)
#model.fit(x_train, y_train, epochs = 100, batch_size = 32)


Epoch 1/100
1375/1375 [==============================] - 12s 7ms/step - loss: 0.1969 - val_loss: 0.1926
Epoch 2/100
1375/1375 [==============================] - 9s 6ms/step - loss: 0.1912 - val_loss: 0.1871
Epoch 3/100
1375/1375 [==============================] - 9s 6ms/step - loss: 0.1854 - val_loss: 0.1787
Epoch 4/100
1375/1375 [==============================] - 9s 7ms/step - loss: 0.1718 - val_loss: 0.1472
Epoch 5/100
1375/1375 [==============================] - 9s 7ms/step - loss: 0.1274 - val_loss: 0.0868
Epoch 6/100
1375/1375 [==============================] - 9s 6ms/step - loss: 0.0764 - val_loss: 0.0565
Epoch 7/100
1375/1375 [==============================] - 9s 6ms/step - loss: 0.0522 - val_loss: 0.0381
Epoch 8/100
1375/1375 [==============================] - 9s 6ms/step - loss: 0.0655 - val_loss: 0.1603
Epoch 9/100
1375/1375 [==============================] - 9s 7ms/step - loss: 0.1558 - val_loss: 0.1399
Epoch 10/100
1375/1375 [==============================] - 9s 6ms/step - 

In [67]:
model.save("model_weight99.79%.h5")

In [62]:
num_of_test_data=13744
time_step=36
seq_len=1
x_test = np.reshape(x_test, (num_of_test_data,time_step ,seq_len))

In [63]:
predictions = model.predict(x_test)


In [64]:
predictions=np.around(predictions,decimals=0,out=None)

print(predictions.shape)
print(len(predictions))
print(predictions)

(13744, 7)
13744
[[0. 1. 0. ... 1. 1. 0.]
 [1. 1. 0. ... 1. 1. 0.]
 [1. 1. 1. ... 1. 1. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 1. 1.]
 [0. 1. 0. ... 1. 1. 0.]]


In [65]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, f1_score
rfc_accuracy = round((accuracy_score(y_test, predictions) * 100), 2)
print("Accuracy : " , rfc_accuracy , " %")

Accuracy :  99.79  %
